In [1]:
import numpy as np

import pandas as pd


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [36]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [38]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [39]:
list2 = [40,50,60]

In [40]:
list3 = [my_list, list2]

In [41]:
list3

[[1, 2, 3], [40, 50, 60]]

In [43]:
arr3 = np.array(list3)

### 

In [45]:
arr3

array([[ 1,  2,  3],
       [40, 50, 60]])

In [46]:
arr3.shape

(2, 3)

In [47]:
#Matrix operation 
# allow us to multiply several things 

In [48]:
arr3 * 3

array([[  3,   6,   9],
       [120, 150, 180]])

In [53]:
lst1 = np.arange(0,13)

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr1 = np.array(lst1)

In [57]:
# 2d

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45], [50,69,85]))

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 69, 85]])

In [75]:
arr_2d.shape

(4, 3)

In [71]:
arr_3d = np.array( [[[ 1,  2, 1,  2],
        [ 3,  4, 1,  2]],

       [[ 5,  6, 1,  2],
        [ 7,  8, 1,  2]],

       [[ 9, 10, 1,  2],
        [11, 12, 1,  2]]])

In [72]:
arr_3d

array([[[ 1,  2,  1,  2],
        [ 3,  4,  1,  2]],

       [[ 5,  6,  1,  2],
        [ 7,  8,  1,  2]],

       [[ 9, 10,  1,  2],
        [11, 12,  1,  2]]])

In [73]:
arr_3d.shape

(3, 2, 4)

In [77]:
np.linspace(12,1)

array([12.        , 11.7755102 , 11.55102041, 11.32653061, 11.10204082,
       10.87755102, 10.65306122, 10.42857143, 10.20408163,  9.97959184,
        9.75510204,  9.53061224,  9.30612245,  9.08163265,  8.85714286,
        8.63265306,  8.40816327,  8.18367347,  7.95918367,  7.73469388,
        7.51020408,  7.28571429,  7.06122449,  6.83673469,  6.6122449 ,
        6.3877551 ,  6.16326531,  5.93877551,  5.71428571,  5.48979592,
        5.26530612,  5.04081633,  4.81632653,  4.59183673,  4.36734694,
        4.14285714,  3.91836735,  3.69387755,  3.46938776,  3.24489796,
        3.02040816,  2.79591837,  2.57142857,  2.34693878,  2.12244898,
        1.89795918,  1.67346939,  1.44897959,  1.2244898 ,  1.        ])

In [78]:
arr_2d[1]

array([20, 25, 30])

In [79]:
arr_2d[1][1]

25

In [80]:
arr_2d[1][1]

25

In [82]:
arr_2d[:1,1]

array([10])

In [83]:
arr_3d.sum()

96

In [85]:
arr_3d.std()

3.5118845842842465

In [86]:
arr_3d.mean()

4.0

In [88]:
arr_3d.mean(0)

array([[5., 6., 1., 2.],
       [7., 8., 1., 2.]])

In [90]:
for x in arr_3d:
    print(x)

[[1 2 1 2]
 [3 4 1 2]]
[[5 6 1 2]
 [7 8 1 2]]
[[ 9 10  1  2]
 [11 12  1  2]]


In [93]:
for x in np.nditer(arr3):
    print(x)

1
2
3
40
50
60


In [95]:
np.save("new_array",arr_3d)

In [96]:
np.savetxt("new_array.txt", arr3, delimiter='t')

In [99]:
np.loadtxt("new_array.txt", delimiter='t', dtype=int)

array([[ 1,  2,  3],
       [40, 50, 60]])